version: '3.4'
services:
  backend:
    build:
      context: ./backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www:rw
    depends_on:
      - db
    tty: true
  frontend:
    build:
      context: ./frontend
      target: ${APP_ENV:-production}
    volumes:
      - ./frontend:/app
      - /app/dist
    tty: true
  web:
    build:
      context: web
      target: ${APP_ENV:-production}
    ports:
      - "24678:24678"
    volumes:
      - ./web:/app
      - /app/.nuxt
      - /app/.output
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www:ro
    depends_on:
      - backend
      - web
      - frontend
    deploy:
      replicas: 1
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-uN3kU4aZ9k}
      MYSQL_DATABASE: ${DB_DATABASE:-lk_mack}
      MYSQL_USER: ${DB_USERNAME:-mack-bd}
      MYSQL_PASSWORD: ${DB_PASSWORD:-uN3kU4aZ9k}
  redis:
    image: "redis:alpine"
    #ports:
    #  - "6379:6379"
volumes:
  db_data: